Feature/set permissions
CERP/MIS pull request #272
Opened 2020-09-01 15:34 UTC by HumnaAleem

2020-09-01 20:43 UTC, Mudassar045 requested changes
Everything seems good, but will take another look in the morning by pulling it on local machine and do some experiments.

2020-09-01 20:43 UTC, Mudassar045 commented on web/src/modules/Landing/index.js
> +		const family_permission = user.permissions && user.permissions.family;
Do you think we should set `false` to all permission variables? Or `true` as we did earlier.

2020-09-01 20:43 UTC, Mudassar045 commented on web/src/typings.d.ts
>  	}
Do we need this anymore?

2020-09-01 20:43 UTC, Mudassar045 commented on web/src/modules/Attendance/index.tsx
> +		const setupPage = current_faculty.permissions && current_faculty.permissions.setupPage
What if current_faculty (logged in user) don't have `permissions` property ?

2020-09-01 20:43 UTC, Mudassar045 commented on web/src/modules/Expenses/index.tsx
> +		const {Admin: admin, permissions} = this.props.user;
can you fix the code `alignment` ? This should be `{ Admin: admin, permissions }`

2020-09-01 20:43 UTC, Mudassar045 commented on web/src/modules/Student/Single/index.js
> +	// permissions: state.db.settings.permissions,
If we don't getting permissions, just remove it instead of commenting out.

2020-09-02 11:37 UTC, HumnaAleem commented on web/src/modules/Expenses/index.tsx
> +		const {Admin: admin, permissions} = this.props.user;
done

2020-09-02 11:38 UTC, HumnaAleem commented on web/src/modules/Student/Single/index.js
> +	// permissions: state.db.settings.permissions,
done

2020-09-02 11:39 UTC, HumnaAleem commented on web/src/modules/Attendance/index.tsx
> +		const setupPage = current_faculty.permissions && current_faculty.permissions.setupPage
It will return undefined and show false case.

2020-09-02 11:43 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +		const family_permission = user.permissions && user.permissions.family;
I think we should set `false` to all permissions because the previous faculty shouldn't have the permission to perform admin tasks.

2020-09-03 11:57 UTC, Mudassar045 approved these changes

2020-09-03 11:58 UTC, merged