Fix/generate payments
CERP/MIS pull request #276
Opened 2020-09-09 07:18 UTC by HumnaAleem

2020-09-09 08:01 UTC, Mudassar045 requested changes

2020-09-09 08:01 UTC, Mudassar045 commented on web/src/modules/Landing/index.js
> +	}
If you change the logic of storing keys values using Object, do change here accordingly. Also I'm not sure it will run for first day, it will start execute from Next day, but I think it's not a problem.

2020-09-09 08:01 UTC, Mudassar045 commented on web/src/modules/Landing/index.js
> +			const sibling_payments = students
Keep consistent variable naming, change `sibling_payments`

2020-09-09 08:57 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +        localStorage.setItem('generatePayments', false);
ok

2020-09-09 10:30 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +	}
done

2020-09-09 10:30 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +			const sibling_payments = students
done

2020-09-09 10:30 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +        localStorage.setItem('generatePayments', false);
done

2020-09-10 07:47 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +			const sibling_payments = students
done

2020-09-10 07:47 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +	}
done

2020-09-10 07:47 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +        localStorage.setItem('generatePayments', false);
done

2020-09-14 11:20 UTC, merged