Feature/targeted instruction
CERP/MIS pull request #282
Opened 2020-10-09 08:25 UTC by HumnaAleem

2020-10-13 18:22 UTC, taimur38 requested changes
Lots of places where logic can be simplified.

The biggest area to improve is reducing the number of state variables we are keeping. If a state variable is a function of another state variable and / or props, then it does not need to be a state variable. This will simplify the logic all throughout the components.

We should also avoid using code that has side effects, and look to see where combinations of map / filter / reduce can more cleanly express the values that we are going for. Some examples are given

2020-10-13 20:05 UTC, taimur38 commented on web/src/actions/index.ts
> +		}
path should be [db, students, student_id, diagnostic_result, test_id] etc

2020-11-13 09:39 UTC, taimur38 reviewed
looks good

2020-11-13 09:39 UTC, taimur38 commented on web/src/typings.d.ts
> +		pdf_links: string
I think we also need to have subject here

2020-11-13 09:39 UTC, taimur38 commented on web/src/typings.d.ts
> +		pdf_links: string
and would need to add it to the csv template as well

2020-11-13 11:49 UTC, taimur38 requested changes
Just a few things to update. Looking much better though

2020-11-13 11:49 UTC, taimur38 commented on web/src/modules/TargetedInstruction/index.tsx
> +							<label className="no-print">Students</label>
can simplify the logic I think.
```javascript
( (type !== 'All Students' && loc === 'report') || (loc === 'grades') ) && <div className="row">.... 
```

2020-11-13 11:49 UTC, taimur38 commented on web/src/modules/TargetedInstruction/index.tsx
> +				{loc === 'test' ? <Diagnostic label={pdfLabel} url={pdfUrl} /> :
For a lot of the logic here, it may make more sense to set up `<Routes>` like we do in the other module. For example, look at student/single/index

2020-11-13 11:49 UTC, taimur38 commented on web/src/modules/TargetedInstruction/index.tsx
> +			return { ...agg, }
can just return agg

2020-11-13 11:49 UTC, taimur38 commented on web/src/modules/TargetedInstruction/style.css
> +}
we must have existing classes which handle this...

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/getSubjectsFromClasses.tsx
> +export default getSubjectsFromClasses;
Why do we need this? Can't you already just go through classes and get the subjects.

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +export const createReport = (students: RootDBState["students"], targeted_instruction: RootDBState["targeted_instruction"], testId: string) => {
can you add comments which describe these functions - important for the util functions

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +                            const category = targeted_instruction && targeted_instruction.slo_mapping[slo[0]] && targeted_instruction.slo_mapping[slo[0]].category;
this only works if there is only one SLO for the question

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +                            const category = targeted_instruction && targeted_instruction.slo_mapping[slo[0]] && targeted_instruction.slo_mapping[slo[0]].category;
```javascript
const categories = slo.map(s => targeted_instruction.slo_mapping[s].category)
```

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +                        .reduce((agg2: MISReport, { isCorrect, slo }) => {
rename agg2 to report

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +export const createReport = (students: RootDBState["students"], targeted_instruction: RootDBState["targeted_instruction"], testId: string) => {
I also think it would be better to just make a function called createReport which creates it for only ONE student. Then wherever you need to create a report, the component can do the work of doing the outer reduce for all students. you don't need to do it here

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +                            const category = targeted_instruction && targeted_instruction.slo_mapping[slo[0]] && targeted_instruction.slo_mapping[slo[0]].category;
```javascript
const augmented_slos = slo.map(s => { category: targeted_instruction.slo_mapping[s] })
const c = isCorrect ? 1 : 0 

return augmented_slos.reduce( (updated_report, curr_slo) => {
    const category = curr_slo.category;
    if(report[category]) {
        const prev = report[category]
        return {
            ...updated_report,
            [category]: {
                correct: prev.correct + c,
                possible: prev.possible + 1,
                link: curr_slo.link
            }
      }
   }

    return {
        ...updated_report,
        [category]: {
            correct: c,
            possible: 1,
            link: curr_slo.link
    }
}, report)
```

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +                                        percentage: c / 1 * 100,
percentage is a **derived** field. So you should not save it, rather whenever you want to use the percentage you can just calculate it from possible and correct.

2020-11-13 11:49 UTC, taimur38 commented on web/src/utils/targetedInstruction.tsx
> +export const getAllStdData = (stdReport: Report) => {
can you explain this function to me on phone

2020-11-16 12:24 UTC, HumnaAleem commented on web/src/constants/targetedInstruction.ts
> +]
testing

2020-11-17 14:41 UTC, HumnaAleem commented on web/src/modules/TargetedInstruction/index.tsx
> +							<label className="no-print">Students</label>
If i do (type !== 'All Students' && loc === 'test')  . It doesn't work according to requirments

2020-11-24 11:28 UTC, taimur38 commented on web/src/actions/core.ts
> +				dispatch(fetchTargetedInstruction())
this should be in src/index.js as:

```javascript
syncr.on('connect', () => dispatch(fetchTargetedInstruction())
```

2020-11-24 11:28 UTC, taimur38 commented on web/src/actions/core.ts
> +export const getTargetedInstruction = () => ({
all this logic should go in actions/index

2020-12-04 12:59 UTC, taimur38 commented on web/src/actions/index.ts
> +		}))
make sure syncr is connected first, and if not, set this action to be dispached with `syncr.onNext('connect', () => dispatch(fetchTargetedInstruction()))`

2020-12-04 12:59 UTC, taimur38 commented on web/src/modules/Landing/index.js
> +	visible: state.db.targeted_instruction_access,
make sure you set this value if it is undefined.

2020-12-06 18:18 UTC, HumnaAleem commented on web/src/modules/Landing/index.js
> +	visible: state.db.targeted_instruction_access,
yup, I set a false value by default.

2020-12-06 18:18 UTC, HumnaAleem commented on web/src/actions/index.ts
> +		}))
ok

2020-12-21 15:32 UTC, merged