Ilmx version
CERP/MIS pull request #286
Opened 2020-10-20 17:46 UTC by HumnaAleem

2020-10-21 12:35 UTC, Mudassar045 requested changes
A few changes required, but also we need to test it rigorously, so that both ilmxUser version and mis normal user version works fine.

2020-10-21 12:35 UTC, Mudassar045 commented on web/src/modules/Front/index.js
> +				<a href="tel:+923481112004">{helpLine.phoneAlt}</a>
in `href` phone number not changed, it should be helpline.phoneInt (verify this)

2020-10-21 12:35 UTC, Mudassar045 commented on web/src/modules/Student/Single/Create/index.tsx
> -					<div className="row">
when the user is `ILMX`, creating new student showing blank page.

2020-10-21 12:35 UTC, Mudassar045 commented on web/src/modules/Teacher/Single/Create/index.tsx
>  				<div className="divider">Personal Information</div>
here the check should be `!this.props.ilmxUser`, if you don't do this, in normal user mode, showing all the fields.

2020-10-21 12:35 UTC, Mudassar045 commented on web/src/modules/Teacher/Single/Create/index.tsx
>  					<div className="divider">Personal Information</div>
Also it should be `!this.props.ilmxUser` for both places

2020-10-21 12:40 UTC, Mudassar045 commented on web/src/modules/Analytics/index.tsx
> +				}
We don't need to hide ilmxechange video analytics `/analytics/ilmexchange` for ilmx user. It will be accessible from landing page

2020-10-22 07:39 UTC, HumnaAleem commented on web/src/modules/Student/Single/Create/index.tsx
> -					<div className="row">
resolved

2020-10-22 07:39 UTC, HumnaAleem commented on web/src/modules/Teacher/Single/Create/index.tsx
>  				<div className="divider">Personal Information</div>
There is no need to add ilmxUser check

2020-10-22 07:39 UTC, HumnaAleem commented on web/src/modules/Teacher/Single/Create/index.tsx
>  					<div className="divider">Personal Information</div>
There is no need to add ilmxUser check

2020-10-22 07:40 UTC, HumnaAleem commented on web/src/modules/Analytics/index.tsx
> +				}
done

2020-10-22 07:42 UTC, Mudassar045 approved these changes

2020-10-22 07:43 UTC, merged