Feedback signup
CERP/MIS pull request #289
Opened 2020-10-26 14:21 UTC by HumnaAleem

2020-10-26 18:09 UTC, Mudassar045 requested changes

2020-10-26 18:09 UTC, Mudassar045 commented on web/src/constants/generic.ts
I think your `vs-code` linter is not working. We need to look into it.

2020-10-26 18:09 UTC, Mudassar045 commented on web/src/modules/Front/SignUp.js
> +			return <Redirect to="/school-login" />
I don't think it should be here. This should be in `render()`

2020-10-26 18:09 UTC, Mudassar045 commented on web/src/modules/Front/SignUp.js
> +					</select>
Did you confirm with Ayesha to show all the district for `PUNJAB` only? If she says show all districts, then you should display all instead of `PUNJAB`

2020-10-26 18:09 UTC, Mudassar045 commented on web/src/modules/Front/SignUp.js
> +				<div className="button red" onClick={() => this.onSave()}> Create Login</div>
I know Ayesha said this to be `Create Login` but it should `Signup` or `Signup for Free-Trial` because the form title is `Sign up`

2020-10-26 18:09 UTC, Mudassar045 commented on web/src/utils/getDistrictTehsilList.ts
> +			"BARNALA",
This should be in constants directory, no?

2020-10-27 11:35 UTC, HumnaAleem commented on web/src/modules/Front/SignUp.js
> +					</select>
Yes, I asked her.

2020-10-28 08:15 UTC, merged