client device time check
CERP/MIS pull request #295
Opened 2020-11-16 08:12 UTC by Mudassar045

2020-11-24 12:50 UTC, taimur38 requested changes
I think there are many good ideas in here. But also a lot of over-engineering, and introducing lots of new things which don't need to be introduced. The logic for checking time is very simple - but through all the various files and function splitting, it is very tedious to follow.

2020-11-24 12:50 UTC, taimur38 commented on web/src/modules/Landing/index.js
> +				</div>}
Why are we showing activation code modal on the timezone bar?

2020-11-24 12:50 UTC, taimur38 commented on web/src/services/appService.ts
> +}
what's the benefit of splitting into so many functions.

```javascript
fetch(`{baseURL}/server-time`)
    .then(res => res.json())
```

2020-11-24 12:50 UTC, taimur38 commented on web/src/services/appService.ts
> +}
There is a lot of extra logic going on, and I am not sure what the benefits are of it.

2020-11-24 12:50 UTC, taimur38 commented on web/src/services/appService.ts
> +			const error = (json_resp && json_resp.message) || text || response.statusText || 'fetch-error'
here is not where you check response.ok - response.text() would error... and you would use catch.

2020-11-24 12:50 UTC, taimur38 commented on web/src/services/index.ts
> +export * from './appService'
Why create an index, and an appService file? what other kinds of services would we create?

I actually don't think this needs to be in a service file at all. We already have a utils folder for these kinds of things -- I think ideally you simply have utils/checkTimes.ts

2020-11-24 12:50 UTC, taimur38 commented on web/src/utils/helpers.ts
>  	// using tilde(~) instead of Math.floor()
why?

2020-11-24 12:50 UTC, taimur38 commented on web/src/utils/helpers.ts
>  	// using tilde(~) instead of Math.floor()
it is much less readable

2020-11-24 12:50 UTC, taimur38 commented on web/src/utils/helpers.ts
> + * @return big integer
this descriptoin is not accurate... this function takes in a timestamp and returns a string showing hours minutes seconds..

2020-11-24 12:50 UTC, taimur38 commented on web/src/utils/helpers.ts
> +	showScroll
Why have you started introducing this export style? What is the benefit

2020-11-24 12:50 UTC, taimur38 commented on web/src/helpers/index.ts
> +export * from './hostConfig'
why have helpers / hostConfig? we already have utils

2020-11-24 12:50 UTC, taimur38 commented on web/src/actions/index.ts
> +import { Dispatch } from 'redux'
typically just use Function to describe Dispatch instead of the type as the default does not handle thunk actions properly

2020-11-25 02:40 UTC, Mudassar045 commented on web/src/actions/core.ts
> +import { getServerTime } from './index'
Then I can `dispatch` from `web/src/idnex.js` where it makes more sense. like

```
syncr.on('connect', () => store.dispatch(getServerTime())
```

2020-11-25 02:40 UTC, Mudassar045 commented on web/src/constants/actionTypes/index.ts
> +enum AppActionTypes {
No the name isn't being used by something else. This is to make distinction in future, among other redux actions types which we hard-coded or exported from  actions/index. For example, We have School, Teachers etc

```
enum SchoolActionTypes {
    SIGNUP = 'SCHOOL_SIGNUP', // this can be used for syncr action type
    SIGNUP_SUCCEED = 'SCHOOL_SIGNUP_SUCCEED'
    .
    .
    .
}
```
So there will be SoC (separation of concern) for what action is about for e.g. SchoolActionTypes, which makes more sense instead of `ActionTypes`

2020-11-25 02:40 UTC, Mudassar045 commented on web/src/constants/actionTypes/index.ts
> +}
First, `export { }` like normal `named-export` e.g.  export enum AppActionTypes. As I explained below in one of comment, what I did like that. As we're using `TS` so it automatically detects exports from `index.ts` file so we can import from constants directly like:

```
// more concise way
import { AppActionTypes } from 'constants/index'

// lengthy way 
import { AppActionTypes } from 'constants/actionTypes/index' // no need to specify 'index' (TS knows)
```
Note: Ideally it should only be imported from `constants` only, but someone intentionally or unintentionally puts `constants` module as `node` dependency, so TS detect first from node_modules

2020-11-25 02:41 UTC, Mudassar045 commented on web/src/modules/Landing/index.js
> +				</div>}
That's my bad. onClick shouldn't be here.

2020-11-25 02:41 UTC, Mudassar045 commented on web/src/services/appService.ts
> +}
I was not sure too when I did this but the more practically use-case of this you can see in `branch-manager` where actually we're dealing with `https` endpoints. We're we have to write 'https://ilmexchange.com/mis/' for each `fetch-request`. We're pretty sure about the `host-origin` and prefix (in this case 'mis'). So don't you think, it makes more sense to split up instead of duplicating (I prefer duplications instead of unnecessary abstractions most of the time :p )

2020-11-25 02:41 UTC, Mudassar045 commented on web/src/services/appService.ts
> +			const error = (json_resp && json_resp.message) || text || response.statusText || 'fetch-error'
I can take a look into it. I wanted to make it generic, I guess I missed it out.

2020-11-25 02:44 UTC, Mudassar045 commented on web/src/services/index.ts
> +export * from './appService'
I can think more about it. The reason behind doing this, we may be using some kind of services (different type of server endpoints, so it basically make no sense to put them in `utils` (we're not reusing anything if we do). I put like this, for only the future use-case.

2020-11-25 02:44 UTC, Mudassar045 commented on web/src/utils/helpers.ts
>  	// using tilde(~) instead of Math.floor()
I wrote the reason in one of reply.

2020-11-25 02:44 UTC, Mudassar045 commented on web/src/utils/helpers.ts
> + * @return big integer
This is unnecessary here. I forgot to remove it along with utility I wrote.

2020-11-25 02:44 UTC, Mudassar045 commented on web/src/utils/helpers.ts
> +	showScroll
Like there no perf benefits or some else. Instead of writing `export` on each single function definition, shouldn't be better to write `export` once and also if we follow this, we can take advantage of `renaming exports` which means we can introduce new export function name irrespective of what is previously written. For example

```
const foo = () => // returning something
const bar = () => // returning something

export {
      foo as helloWorld(),
      bar as doSomething()
} 
```
For that reason, I started practicing this.

2020-11-25 02:44 UTC, Mudassar045 commented on web/src/helpers/index.ts
> +export * from './hostConfig'
Yeah you're right. I wasn't sure about this `helpers` directory. This all other places, I did stuff intentionally to carry out discussion about the patterns, conventions and some best practices for code splitting.

2020-11-25 02:44 UTC, Mudassar045 commented on web/src/actions/index.ts
> +import { Dispatch } from 'redux'
Again that's my bad but "does not handle thunk actions properly", how a type `Dispatch`, can cause any issue to thunk?

2020-11-25 03:00 UTC, Mudassar045 commented
> I think there are many good ideas in here. But also a lot of over-engineering, and introducing lots of new things which don't need to be introduced. The logic for checking time is very simple - but through all the various files and function splitting, it is very tedious to follow.

Thanks for looking into it. The sole intent purpose of writing down, splitting code and introduce new stuff, is to carry out discussion about some kind of conventions, coding best practices to follow while coding as team on a single or multiple projects. Code should belong to a team not to a single person. So anyone don't introduce new tedious ways (pardon me, I do :p), which reflects individual practice. This is ensure, the new joiners or anyone later can see clearly what to follow or what to not. That's all I want to say in above replies.

2020-12-17 09:28 UTC, merged