Added Expense pages and form to edit an expense
CERP/MIS pull request #325
Opened 2021-04-26 10:57 UTC by hamzaahmed00

1. Added the Expense page
2. Added form to edit/add an expense

2021-04-26 17:47 UTC, mudssrali requested changes
Hi 👋 @hamzaahmed00 , Congratulations for your First PR 🥳 and looks good to me.
Good work in terms of layout designing and a few logic constructs. Appreciate your dedication and keeping flow in mind while working on expense module. Here is a few things that you work on them:
- Avoid using `inline-styles` and `any`
- Make your familiar with falsy values, `reduce()` and `moment()`
- Take care while naming a variable and and use of  typings
- Avoid using alert (it halts code execution), use toast instead

Also left a few questions in reviews comment, would expect your response on them.

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/expenseForm/index.tsx
> +	const expense: any = useSelector((state: RootReducerState) => state.db.expenses[key])
You can split this into two statements
```ts
   const { expenses } = useSelector((state: RootReducerState) => state.db)
   const expense = expenseId ? expenses[expenseId]: undefined
```

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/expenseForm/index.tsx
> +						/>
We can simply use `<input ... />`, for now with already custom utilities

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/expenseForm/index.tsx
> +							})}
Always remember to have `key` when you're using `map()` as
```ts
categories.map(cat => (
     <div key={cat} ... />
))
```
Also as said above, avoid using `inline-styles`, you can use tailwindcss utilities. To generate className string conditionally, there's utility already setup that you can use as:

```ts
import clsx from 'clsx'
.
.
.
    <div className={clsx('rounded-full p-1 mt-1 text-gray-200 text-xs border-gray-200 border-2',
     state.category === cat ? 'bg-something' : 'bg-something')} />
```

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/expenseForm/index.tsx
> +								}
```ts
onChange={(e) =>
	setState({
		...state,
		date: e.target.valueAsNumber // will give time in unix-timestamp
	})
}
```

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/expenseForm/index.tsx
> +									: '0'}
Same goes here above `inline-styles` and `falsy` values

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/index.tsx
> +		}
also, `moment()` can be used here as well

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/index.tsx
> +
Types can be extracted a single type and also here again use `reduce()` as said above

2021-04-26 17:47 UTC, mudssrali commented on web/src/pages/expense/index.tsx
> +				</div>
It would be better to apply `groupedResults &&` on parent element. Also avoid using `any` and provide `key`

2021-04-26 17:47 UTC, mudssrali commented on web/src/routing/index.tsx
> +						<Route path="/expenses/:id" exact component={ExpenseForm} />
These are private routes, so you can use `<PrivateRoute />` instead of `<Route />`

2021-04-26 19:59 UTC, hamzaahmed00 commented on web/src/routing/index.tsx
> +						<Route path="/expenses/:id" exact component={ExpenseForm} />
Will do

2021-04-26 20:00 UTC, hamzaahmed00 commented on web/src/pages/expense/index.tsx
> +				</div>
I will apply the groupedResults on the parent element but since we are creating a new type of data structure, I could not get it to work so I settled on any, I will look into this as well

2021-04-26 20:02 UTC, hamzaahmed00 commented on web/src/components/cards/expense/index.tsx
> +}
Isn't it time in milliseconds?

2021-04-26 20:04 UTC, hamzaahmed00 commented on web/src/components/cards/expense/index.tsx
> +}
It was doing string concatenation so to be safe, I just parsed them into float by forcing them to convert to string

2021-04-26 20:04 UTC, hamzaahmed00 commented on web/src/components/cards/expense/index.tsx
> +							</h1>
I will do so

2021-04-26 20:05 UTC, hamzaahmed00 commented on web/src/components/cards/expense/index.tsx
> +				return (
Got it

2021-04-26 20:06 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +}
That expects an id but we are not generating the id here, that is why I just defined a type

2021-04-26 20:07 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +			</div>
Yes I have access to notion, I will look into it

2021-04-26 20:07 UTC, hamzaahmed00 commented on web/src/components/cards/expense/index.tsx
> +const ExpenseCard: FC<propTypes> = ({ expenseData, date }) => {
Okay got it

2021-04-26 20:08 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +		}
Yes, they are integer and I will use toast from now on

2021-04-26 20:09 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +		if (isNew()) {
Okay will do

2021-04-26 22:38 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +	}
I was getting the text that was written in the inner text and assigning it to the category

2021-04-26 22:40 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +	}, [])
I dont get this one

2021-04-26 22:41 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +	let key: string = props.match.params.id
That I forgot to change, I will do that

2021-04-26 22:41 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +	const expense: any = useSelector((state: RootReducerState) => state.db.expenses[key])
Okay

2021-04-26 22:42 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +						/>
I just created this component so that I would not have to apply styling to all the other inputs over and over again

2021-04-26 22:42 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +							})}
Got it

2021-04-26 22:44 UTC, hamzaahmed00 commented on web/src/pages/expense/index.tsx
> +
Got it

2021-04-27 07:33 UTC, mudssrali commented on web/src/components/cards/expense/index.tsx
> +}
yes, it's! I just used for an example.

2021-04-27 13:39 UTC, raoaliahmad requested changes
Overall Good Work, 
Mudassir did a pretty good review so I didn't had much to comment on. 
PS: I have left some comments have a look at them.

2021-04-27 13:39 UTC, raoaliahmad commented on web/src/pages/expense/expenseForm/index.tsx
> +					defaultValue={props.defaultValue}
In React, `defaultValue` is used with uncontrolled form components whereas `value` is used with controlled form components
- `Controlled Components` form data is handled by a React component i.e using onChange
- `Uncontrolled Components` form data is handled by the DOM itself i.e can use a ref to get form values from the DOM

2021-04-27 13:39 UTC, raoaliahmad commented on web/src/pages/expense/expenseForm/index.tsx
> +	const expense: any = useSelector((state: RootReducerState) => state.db.expenses[key])
Instead of returning an object from the selector function i.e `state.db` and then getting expense out of it, only return expense i.e `state.db.expense` 
Because the way `useSelector` works, is that it compare the return value of the selector function with the return value from the prev render and then decides if it needs to re-render or not. It's official docs have really good explanation https://react-redux.js.org/api/hooks

2021-04-27 13:39 UTC, raoaliahmad commented on web/src/pages/expense/expenseForm/index.tsx
> +	const [state, setState] = useState<addExpense>()
instead of leaving the state undefined what you can do is 
```
const initExpense = expense[id] ?? { defaultExpense Object here }
const [state, useState] = useState<addExpense>(initExpense)

useEffect(() => {
   if(expenseId && expense) {
       setState(expense[expenseId])
   }
},[expense])
```

2021-04-28 11:28 UTC, hamzaahmed00 commented on web/src/pages/expense/expenseForm/index.tsx
> +	const [state, setState] = useState<addExpense>()
Why do we need useEffect now?

2021-04-28 19:18 UTC, hamzaahmed00 commented on web/src/pages/expense/index.tsx
> +		}
moment for some reason refuses to work here and messes up my code so left this portion as is

2021-05-06 20:54 UTC, mudssrali requested changes
Good work, Keep up!
Here is a few areas that you need to consider while working and you can improve on them:
- Naming Convention
- Inferring types (implicit and explicit)
- Logic Constructs - JS or Pure ReactJS stuff
- New Language Features

I left a few questions also, please post your quick answer to them.

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +	)
why we're doing this?

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +	const [totalPaid, setTotalPaid] = useState<number>(0)
here also we can create a single state variable using object

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +
First, why we need to calculate `deduction` and `paid` amount in useEffect()?
Second, we can use `reduce()` here and also and can eliminate multiple state setting by having a state object as. 

One thing to `note` here, actually we don't need to store these values in the state, we can just calculate them simply and use as result.
```tsx
	const { deduction, paid } = salaries.reduce(
		(agg, salary) => ({
			deduction: agg.deduction + salary.deduction,
			paid: agg.paid + salary.amount
		}),
		{ deduction: 0, paid: 0 }
	)
```
One thing more, if we have already something e.g. `salaries` as state variable, and we compute result from it, then we don't need to store that result in form of state variable. In short, don't derive state from state

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +			)
I think we agreed on it to change to `addSalaryExpense()` to take an object as param instead of multiple arguments.

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +						deduction_reason: '',
we don't need of doing this, we can get the updated salaries from props, instead of saving them to state variable.

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +					<div className="m-5 text-gray-50 lg:space-y-5">
why we need of  `ref={mainFormRef}` here?

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +							<div>
You can create an `enum` of salary type as
```tsx
enum SalaryType {
FULL,
DEDUCTED,
ADVANCE
}
```
Now in your component
```tsx
const [salaryType, setSalaryType] = useState<SalaryType>()
.
.
.
{ type === SalaryType.FULL && (...) ...}
```

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +					}}
What are we achieving here?

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +								return (
`entry` can be changed to `salary` - naming convention

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/index.tsx
> +			.reduce((agg: { [id: string]: MISSalaryExpense[] }, curr: any) => {
You can do `filter()` part inside `reduce()` to some some computations.

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/index.tsx
> +		console.log('ID is ', groupsByFacultyID[Object.keys(groupsByFacultyID)[0]][0].faculty_id)
make sure, we remove these, anyhow will be removed in my commit

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/index.tsx
> +										}}>
instead of creating route like `/salary/teacher.id`, we should do it as `staff/:id/salaries`

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/index.tsx
> +					</div>
Instead of showing `Last paid` or `Deducted` amount like this, you can pass them from parent component as prop variable which is more explicit what `salary[0].amount` means

2021-05-06 20:54 UTC, mudssrali commented on web/src/pages/expense/salary/index.tsx
> +}
this already exist in `utils/index.ts`

2021-05-06 20:54 UTC, mudssrali commented on web/src/routing/index.tsx
> +						<PrivateRoute path="/salary/:id" exact component={SalaryForm} />
Both these `/salary` and `salary/:id` should be changed to:

- `/staff/salaries` 
- `staff/:id/salaries`

2021-05-06 20:54 UTC, mudssrali commented on web/tailwind.config.js
> +				height: 'max-height'
I didn't know about it before, but it works awesome <3

2021-05-06 22:04 UTC, hamzaahmed00 commented on web/src/pages/expense/index.tsx
> +		})
Because we are sorting the salaries (unsorted by default) from latest date to oldest date, this allows us to get the latest paid salary easily by doing salary[0] as it will always be the salary of the most recent date

2021-05-06 22:06 UTC, hamzaahmed00 commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +	)
I was getting an undefined error for teachers who were never paid a salary without doing this

2021-05-06 22:07 UTC, hamzaahmed00 commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +
I was doing it in useEffect so it could automatically recalculate whenever salaries changes

2021-05-06 22:09 UTC, hamzaahmed00 commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +					<div className="m-5 text-gray-50 lg:space-y-5">
We need that to calculate the exact height and width of this form and apply it to the pop up for past payments so that everything is properly aligned

2021-05-06 22:10 UTC, hamzaahmed00 commented on web/src/pages/expense/salary/SalaryForm/index.tsx
> +					}}
This is for the placement and sizing of the div that appears when we click "view past payments"

2021-05-06 22:18 UTC, hamzaahmed00 commented on web/src/pages/expense/index.tsx
> +		})
Oh no, my mistake this is not for salaries, this actually sorts the expenses so that the latest day always shows up on top, it is not sorted by default so thats why I had to sort

2021-05-17 13:21 UTC, hamzaahmed00 commented on web/src/pages/expense/index.tsx
> +	}
if I don't specify type for expense, it does not let me get the amount from it

2021-05-27 19:48 UTC, merged