Feature/oral tagging
CERP/MIS pull request #335
Opened 2021-05-06 15:32 UTC by HumnaAleem

2021-05-06 21:41 UTC, mudssrali requested changes
There are a few things need to be changed, otherwise seems fine.

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
>  }
it should be `enum ModalType`

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
> +		} = std?.targeted_instruction?.learning_level?.[selected_subject]
this would throw run-time error if something would be undefined on right side of the expression. Please introduce default value for is_oral, history and grade

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
> +		const is_oral = selected_grade === 'Oral Test' ? true : current_oral_value ? true : false
This can be simplified as
```ts
const is_oral = selected_grade === 'Oral test' || current_oral_value
```

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/GroupView/GroupViewCard.tsx
> +}
same here enum should be named as `ModalType`

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/index.tsx
> +		.length
We should be careful while calculating `totalNumberOfStudents`, here you're considering all type of students e.g. in-active, left school, prospective. Add a filter here and then calculate length

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/GroupView/index.tsx
> +	const total_students = Object.values(filtered_students || {}).length
Same here, apply filter before calculating length

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentInfoModal.tsx
> +	}
Here we can pass a single callback function which would be updating values for all of these variable in the parent component, instead of multiple calls in `OnEdit` Function

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentInfoModal.tsx
> +								`text-${grade.toLowerCase()}-tip-brand`
we agreed on not to concatenate and then generate a extended text-color utility. This has been discussed multiple times with a valid reason, why we can't do this.

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentInfoModal.tsx
> +							Edit
Here we don't need to cast sub as TIPSubjects, instead you can check the prototype of `onEdit()` and make it align with `sub` type

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileClassView.tsx
> +						)
what is happening here? Also now it's better to avoid using `||` and make use of `??` everywhere, where you need to check `undefined` or `null` values.

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileClassView.tsx
> +								: convertLearningGradeToGroupName(grade_obj?.grade)
Please add a description here, what is actually happening here and why.

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileGroupView.tsx
> +	)
why we need sorter function to be coded like this?

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileHeader.tsx
> +							/>
```
std?.ProfilePicture?.url ?? std?.ProfilePicture?.image_string ?? WhiteUser
```
Also please change `WhiteUser` to more suitable variable name

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileRow.tsx
> +					})}>
Instead of passing `Yes` | `No` as is_oral variable, Please pass this as boolean prop and if we need Yes|No here, we can do `{ is_oral ? 'Yes' : 'No' }`

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/index.tsx
> +
Good to see `PascalCase` here for enum name

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/FormativeTest/Grading.tsx
> +				]?.targeted_instruction?.learning_level?.[subject]
If this statement result in `undefined` on right side, will throw run-time error, please initialize it with default value

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/FormativeTest/Grading.tsx
> +				const is_oral = level === 'Oral Test' ? true : current_oral_value ? true : false
Same it can be simplified as 
```js
const is_oral = level === 'Oral Test' || current_oral_value
```

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/FormativeTest/Grading.tsx
>  				setModaltype('assign_group_modal')
As said above please describe what's happening here.

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/PDF.tsx
> +	const quiz_title = targeted_instruction?.quizzes?.[class_name]?.[subject]?.[quiz_id].quiz_title
what if `targeted_instruction?.quizzes?.[class_name]?.[subject]?.[quiz_id]` is undefined ?

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Grading.tsx
> +	const quiz_title = targeted_instruction?.quizzes?.[class_name]?.[subject]?.[quiz_id].quiz_title
same goes here, what if `targeted_instruction?.quizzes?.[class_name]?.[subject]?.[quiz_id]` is undefined? would be you able to get `quiz_title` ?

2021-05-06 21:41 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/index.tsx
> +	const quiz_title = targeted_instruction?.quizzes?.[class_name]?.[subject]?.[quiz_id].quiz_title
here as well

2021-05-07 16:16 UTC, HumnaAleem commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileGroupView.tsx
> +	)
It filters alphanumeric values

2021-07-01 00:26 UTC, merged