Enter Marks Redesign
CERP/MIS pull request #418
Opened 2021-08-20 14:50 UTC by hmzahmed

This PR includes the Redesign for Enter Marks sub-module of the module 'Exams'. A high level overview of the features in the PR includes the following:

- Display Exam Cards
- Make filters to filter through exam cards
- Ability to enter marks for a single subject
- Ability to add missing student during entering of single subject marks
- Ability to enter marks in Bulk for term exams and Monthly tests
- Print Marksheet

2021-08-21 12:11 UTC, mudssrali requested changes
Thanks @hmzahmed! It was a big module to redesign and a bunch of new features that newly incorporated. I left a few questions and added comments to improve code quality and logical constructs, please do read all and make a list of common things which we should observe while working on something new or adding tweaks to existing modules.

2021-08-23 07:59 UTC, hmzahmed commented on web/src/components/cards/exams/GroupedExamCard.tsx
> +								examId={exam.id}
I was sending an array and not an object, so this was the bug that was causing undefined error.

2021-08-23 08:11 UTC, hmzahmed commented on web/src/pages/exams/marks/EnterBulkMarks.tsx
> +}
No

2021-08-23 08:12 UTC, hmzahmed commented on web/src/pages/exams/marks/EnterBulkMarks.tsx
> +		const section_id = pq.section_id ? pq.section_id.toString() : ''
Its parsed query, I dont know why we are casting toString, It was the defualt logic

2021-08-23 08:51 UTC, hmzahmed commented on web/src/pages/exams/marks/EnterBulkMarks.tsx
> +			exam_title,
It is defined in typings in this way and is used in many files

2021-08-23 09:43 UTC, mudssrali commented on web/src/pages/exams/marks/EnterBulkMarks.tsx
> +		}
We can do this later.

2021-08-25 08:04 UTC, merged