Changes for HT dashboard
CERP/MIS pull request #450
Opened 2021-09-28 08:01 UTC by hmzahmed

- Changed Colors for Quizzes
- Changed Colors for Lesson Plans
- Changed View For Diagnostic Test
- Changed View for Midpoint Test
- Changed View for Summative Test
- Added Tabs for Comparison Matrix
- Added the functionality which enables the behavior that only questions whose grade is equal or lower that that of the student grade are counted when calculating percentage

2021-09-28 19:03 UTC, mudssrali requested changes
Overall changes look fine to me. Thanks @hmzahmed - However, please make sure to read all comments and make a habit, to not do it again in future PRs. These are general things, we need to keep them on our radar always while working. To write good code:

- Follow the convention e.g. camelCasing
- Whenever possible and need, make reusable constructs
- Don't Repeat Yourself, create once and use it where you need
- Good variable names
- Align with latest changes in the technology.

2021-10-02 15:22 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Tests/MidpointTest/index.tsx
> +	{ level: 'Level 3', color: 'Orange' }
Yes

2021-10-03 18:49 UTC, mudssrali requested changes
Thanks @hmzahmed a lot of improvement, Get ahead! just a change required for level sorting, compare function.

2021-10-03 18:49 UTC, mudssrali commented on web/src/hooks/useTIPStudents.ts
> +	students: RootDBState['students'],
❤️

2021-10-03 18:49 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Lessons/index.tsx
> +				.sort(([level_a, _], [level_b, _noUse]) => levelSorter(level_a, level_b))
We can simply do as we only need array first element:
```tsx
sort(([levelA], [levelB]) =>...)
```
OR
```tsx
sort(([a], [b]) =>...)
```

2021-10-03 18:49 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Lessons/index.tsx
> +										'bg-orange-tip-brand': level === TIPLevelMap.L3
nice.

2021-10-03 18:49 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Quizzes/index.tsx
> +				.sort(([level_a, _], [level_b, _noUse]) => levelSorter(level_a, level_b))
same goes here. However you can create a `comparator-function` as
```tsx
export const compareLevel([a], [b]) => {...}
```

2021-10-03 18:49 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Quizzes/index.tsx
> +										'bg-orange-tip-brand': level === TIPLevelMap.L3
here we go.

2021-10-03 18:49 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/index.tsx
> +						percent: Math.round((calculatedResult.obt / calculatedResult.total) * 100)
I feel `calculatedResult.obt` is previously done.

2021-10-03 18:49 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/MidpointTest/index.tsx
> +	const [view, setView] = React.useState(undefined)
nice.

2021-10-03 18:49 UTC, mudssrali commented on web/src/utils/TIP.ts
> +}
```tsx
export const compareLevels([a], [b]) => {
   a == TIPLevelMap.KG ? -1 : b == TIPLevelMap.KG ? 1 : a.localeCompare(b)
}
```
and we can directly pass this to `sort()` like
```tsx
sort(compareLevels)
```

2021-10-04 07:02 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/index.tsx
> +						percent: Math.round((calculatedResult.obt / calculatedResult.total) * 100)
I dont think so

2021-10-04 11:17 UTC, mudssrali approved these changes

2021-10-04 11:17 UTC, merged