TIP Quizzes Results
CERP/MIS pull request #452
Opened 2021-10-01 11:39 UTC by hmzahmed

- Design changes in Skill View Page
- Map Results to Quiz Titles instead of slos in Skill View Page
- Fix Pagination in child view page
- Design changes in Child View Page
- Map Results to Quiz Titles in Child View Page
- Create Single Quiz View page and remove Single SLO page
- Calculate results for a Single Quiz
- Design Changes in single student quiz result page
- Map results to titles instead of slos in single student quiz result page
- Refactors and tweaks

2021-10-02 18:32 UTC, mudssrali requested changes
Overall it looks good. Thanks @hmzahmed I can see the improvements. However a few questions and some logical tweaks/suggestions commented, do check them.

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +					arrayLength = Math.ceil(Object.keys(quizResult ?? {}).length / 3)
arrayLength... better naming convention.

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +											]?.[quizId] ?? ({} as QuizReport)
same goes here. we need little explanation why and what's happening here.

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +					{numOfPages.map(no => (
what's `no` ?

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +				/>
Nice

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/DetailedQuizResult.tsx
> +					setQuizAndType={(slo, type) =>
`(slo, type)` --> `(quiz, type)`

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/DetailedQuizResult.tsx
> +				<>
we don't of `fragment` here.

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/DetailedQuizResult.tsx
> +					filteredStudents={filteredStudents}
instead of component prop `filteredStudents` -> `students` would be good.

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/SkillView/SingleQuizView.tsx
> +const SingleQuizView: React.FC<P> = ({ singleQuizResult, quiz }) => {
Instead of `P` it would be good to go with:
```tsx
interface SingleQuizViewProps {
...
}
```

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/SkillView/index.tsx
> +	BELOW_AVG = 'belowAverage',
it's fine to have `above_average` and `below_average`

2021-10-02 18:32 UTC, mudssrali commented on web/src/modules/TIP/TIPConstants.ts
> +}
nice that we move it here.

2021-10-02 18:32 UTC, mudssrali commented on web/src/types/typings.d.ts
> +	aboveAverage: number
Are you sure previous school won't affect with these changes? I think we spoke about it because this gonna get us into trouble if we're maintaining this in db for old schools.

2021-10-02 18:32 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		if (studentResult) {
it's better to return early.
```tsx
if(!result) {
 return agg
}

return {
  ...agg,
  [student.id]: {
	  obtainedMarks: studentResult?.obtained_marks ?? 0,
	  totalMarks: studentResult?.total_marks ?? 0,
	  name: student.Name,
	  rollNo: student.RollNumber
  }
}
```

2021-10-02 18:32 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		}, [])
We can do `map()` here
```tsx
.map(quiz => quiz.quiz_title)
```

2021-10-04 10:10 UTC, hmzahmed commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
>  	})
This I have no idea about, I didnt write this logic, I just refactored it to have camel case naming

2021-10-04 10:13 UTC, hmzahmed commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +	let arrayLength = Math.ceil(quizIds?.length / 3)
From all quizIds, we are making a set so that duplicates are removed and then returning those unique values in ascending order

2021-10-04 10:15 UTC, hmzahmed commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +	let numOfPages = [...new Array(arrayLength).keys()]
Because we have to show only 3 tests per page

2021-10-04 10:21 UTC, hmzahmed commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +						.slice(pageNum * 3, (pageNum + 1) * 3)
This is how we are displaying data, we are taking the current page number and multiplying by 3 to give us starting index of slice, then we do the same but add 1 to the number so that it is 3 more than the the starting index. so if the page is 2, we will have the data of quizzes 6,7,8

2021-10-04 10:22 UTC, hmzahmed commented on web/src/modules/TIP/Results/Quiz/ChildView/index.tsx
> +					{numOfPages.map(no => (
pageNumber, I have changed it now

2021-10-04 10:37 UTC, hmzahmed commented on web/src/modules/TIP/Results/Quiz/SkillView/index.tsx
> +	BELOW_AVG = 'belowAverage',
have to change because of change in typings

2021-10-04 10:38 UTC, hmzahmed commented on web/src/types/typings.d.ts
> +	aboveAverage: number
Yes because this is only used when we calculate data in realtime

2021-10-04 14:27 UTC, merged