add multiple passwords to Starting, Oral and Summative tests
CERP/MIS pull request #453
Opened 2021-10-02 18:37 UTC by ZarishIqbal

Added multiple password protection to diagnostic, oral and summative tests.

2021-10-02 20:42 UTC, mudssrali requested changes
Thanks @ZarishIqbal Looks good to me. A few comments about test `type` typings and password.

2021-10-02 20:42 UTC, mudssrali commented on web/src/types/typings.d.ts
> +		}
type typings would be `TIPTestType` and we can simplify like
```tsx
test_password: {
    type: TIPTestType
    password: string
}
```

2021-10-02 20:42 UTC, mudssrali commented on web/src/utils/helpers.ts
> +export const checkPasswordTestType = (testType: string) => {
again testType would be of type `TIPTestType`
```tsx
export const checkPasswordTestType = (type: TIPTestType) => {
...
}
```

2021-10-02 20:42 UTC, mudssrali commented on web/src/utils/indexedDb.ts
> +		}
If we're going to change type of `type` from `string` to `TIPTestType`, we might need do trick here.

2021-10-02 20:42 UTC, mudssrali commented on web/src/utils/localStorage.ts
> +		}
same goes here.

2021-10-02 20:42 UTC, mudssrali commented on web/src/components/TIP/test-password-modal.tsx
> +				payload: { type: testType, password: state.password }
To just share, `data` and `payload` have both same meaning in term of usage. You can literally use any other variable than them but be careful when getting value inside a reducer.

2021-10-02 20:42 UTC, mudssrali commented on web/src/components/TIP/test-password-modal.tsx
> +	Quiz: { abc3: true, abc4: true }
Here we might need to change passwords for `Formative` and `Quiz`, no?

2021-10-02 21:38 UTC, ZarishIqbal commented on web/src/components/TIP/test-password-modal.tsx
> +	Quiz: { abc3: true, abc4: true }
Since quizzes and formative tests aren't password-protected yet, their password doesn't matter for now. I'll remove these.

2021-10-03 08:37 UTC, mudssrali approved these changes
Thanks @ZarishIqbal!

2021-10-03 08:37 UTC, mudssrali commented on web/src/components/TIP/test-password-modal.tsx
> +} as Partial<PasswordMapping>
makes sense, nice

2021-10-03 08:37 UTC, merged