Tip/zarish/fixes
CERP/MIS pull request #468
Opened 2021-11-05 07:09 UTC by ZarishIqbal

- Tags should show up only if student was re-assigned 
- Make inappropriate options during re-assignment blurred
- Lesson plans download
- Video icon on lesson plans on video
- Show password option

2021-11-07 17:14 UTC, mudssrali requested changes
Thanks @ZarishIqbal for the changes. I pointed-out some areas of code logic where we can improve on and  make sure we make habit to keep focus while introducing any change in the existing or as new feature. Moreover I understand that we need all to align and refactor all existing codebase to conform with our set of rules for naming and working in co-working space.

2021-11-07 17:14 UTC, mudssrali commented on web/src/modules/TIP/LessonPlans/List.tsx
> +			const quiz = targetedInstruction?.quizzes?.[class_name]?.[subject]?.[quiz_id]
till `targetedInstruction.quizzes[class_name]` we don't need to have a `? - optional chaining operator`. so
```tsx
const quiz = targetedInstruction.quizzes.[class_name]?.[subject]?.[quiz_id] ?? {}
```

Adding `?? { }` to avoid any run-time issue.

2021-11-07 17:14 UTC, mudssrali commented on web/src/modules/TIP/LessonPlans/List.tsx
> +}))(List)
we can get rid of this as well and use `useDispatch()` to dispatch required actions.

2021-11-07 17:14 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		// @ts-ignore
why do need this?

2021-11-07 17:14 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		})
❤️ 💚

2021-11-07 17:14 UTC, mudssrali commented on web/tailwind.config.js
> +				'light-teal-brand': '#15C6CE',
all `TIP` extended colors must have `tip` string part e.g. `light-tip-teal-brand`.

2021-11-08 03:04 UTC, ZarishIqbal commented on web/src/modules/TIP/LessonPlans/List.tsx
> +			const quiz = targetedInstruction?.quizzes?.[class_name]?.[subject]?.[quiz_id]
There is an error due to null coalescing. We cannot avoid runtime issues in this way

2021-11-08 04:34 UTC, mudssrali approved these changes
Thanks @ZarishIqbal - LGTM 👍🏻

2021-11-08 04:34 UTC, merged