Fixes/1.2.5
CERP/MIS pull request #475
Opened 2021-11-18 10:20 UTC by ZarishIqbal

### Fixes
- add revision type to lesson plans
- design tweaks

2021-11-19 07:33 UTC, mudssrali requested changes
LGTM - Thanks @ZarishIqbal - I write some suggestions/comments below.

2021-11-19 08:01 UTC, ZarishIqbal commented on web/src/modules/TIP/DetailedAnalysis/Modals/TIPGroupModal.tsx
> +										{
Because earlier they asked me to grey it out but now they want a faded version of the same color.

2021-11-19 08:02 UTC, ZarishIqbal commented on web/src/modules/TIP/DetailedAnalysis/Modals/TIPGroupModal.tsx
> +										{
> why we changed from `ternary-operator` to and-conditional (`&&`) statement ?

Because earlier they asked me to grey it out but now they want a faded version of the same color.

2021-11-19 08:03 UTC, ZarishIqbal commented on web/src/modules/TIP/LessonPlans/List.tsx
> +													lessonPlan.type === 'revision'
> it would be a good practice to go with `upper-case` string literals e.g. `REVISION`

Okay

2021-11-19 08:05 UTC, ZarishIqbal commented on web/src/types/typings.d.ts
> +	type: string
> instead of `type: string` doing this, we can do
> 
> ```tsx
> type: 'REVISION' | 'SOMETHING' | 'SOMETHING' 
> ```

```tsx
 type: 'REVISION' | 'NEW' ?
 ```

2021-11-21 22:05 UTC, mudssrali commented
This PR is closed because of #476

2021-11-21 22:05 UTC, closed without merging