TIP Sprint 3
CERP/MIS pull request #479
Opened 2021-11-27 08:26 UTC by ZarishIqbal

- Change order of modules on TIP homepage
- Change order of subjects in all modules

2021-11-29 08:17 UTC, mudssrali requested changes
Thanks @ZarishIqbal - Looks good to me. Just a few questions

2021-11-29 08:17 UTC, mudssrali commented on web/src/modules/TIP/LessonPlans/PDF.tsx
> +								<div className="bg-teal-brand pb-1 h-20 mx-3 rounded-md mb-3 flex flex-row justify-between items-center px-2 shadow-lg">
as we remove `<a.../>` Are we still able to download? I don't see any `onClick(...)` on `<div.../>` tag.

2021-11-29 08:17 UTC, mudssrali commented on web/src/modules/TIP/index.tsx
> +						<img className="w-20 h-20" src={BlueQuiz} alt="img" />
better practice `alt` attribute must have descriptive name e.g. `quiz-icon`

2021-11-29 08:17 UTC, mudssrali commented on web/src/modules/TIP/Card.tsx
> -									)}`}
why we're getting rid of this?

2021-11-29 08:28 UTC, ZarishIqbal commented on web/src/modules/TIP/HTDashboard/Lessons/index.tsx
> +								.sort((a, b) => (a === 'English' ? -2 : a === 'Urdu' ? -1 : 1))
They wanted it to be 
English
Urdu
Math

2021-11-29 08:46 UTC, ZarishIqbal commented on web/src/modules/TIP/LessonPlans/PDF.tsx
> +			<a ref={downloadLinkRef} href={'#!'} className="hidden" />
@mudssrali I haven't removed it. Just kept it outside so that I can be used for both the downloads.

2021-11-30 11:46 UTC, ZarishIqbal commented on web/src/modules/TIP/Card.tsx
> -									)}`}
[https://cerp-labs.atlassian.net/browse/TIP-13?atlOrigin=eyJpIjoiNzY2Yzk1M2IzYzM2NDI1OTk0YzU3M2IxN2FjOTU0YjkiLCJwIjoiaiJ9](url)

Its a task.

2021-12-03 03:55 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Lessons/index.tsx
> +								.sort((a, b) => (a === 'English' ? -2 : a === 'Urdu' ? -1 : 1))
instead of this weird sort function, we can bring in order-map of subjects and based on order we can do a simple sort

2021-12-05 20:37 UTC, mudssrali approved these changes
Thanks @ZarishIqbal - All look fine to me. I refactor code a bit to make sure we have single source of TIP subjects in MISchool - TIP Tool

2021-12-05 20:37 UTC, merged