TIP Patch 1
CERP/MIS pull request #481
Opened 2021-11-29 11:52 UTC by hmzahmed

2021-11-29 11:57 UTC, hmzahmed commented
Not ready for merge yet

2021-11-29 13:34 UTC, mudssrali requested changes
Thanks @hmzahmed - Looks good to me. A few changes and suggestions in the comments. We need to update documentation about new changes that we introduce.

2021-11-29 13:34 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Sorting/index.tsx
>  	WT_missing: { [sub: string]: number }
What is `Missing`? Also we can improve this as
```tsx
type Missings = 'OT' | 'OT_NEEDED' | 'WT'
type MissingTypes = {
  [key in Missings]: {
    [subject: string]: number
  }
}

2021-11-29 13:34 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/DetailedQuizResult.tsx
>  		[]
instead of applying `filter(...)` we can filter-out in the calling function `getSkillViewQuizResult(...)`

2021-11-29 13:34 UTC, mudssrali commented on web/src/modules/TIP/Results/Quiz/DetailedQuizResult.tsx
> +	console.log(skillViewResult)
clean this up.

2021-11-29 13:34 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		'Class 5': '3'
first `conversionMap` and Is this correct map?

2021-11-29 13:34 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Sorting/index.tsx
> +						...missing['OT_needed'],
as you're introducing a new `OT_needed` property, it would throw an error because `missing[OT_needed]` will result in `undefined` value and spreading undefined would cause run-time error

2021-11-29 13:34 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Sorting/index.tsx
> +						[sub]: (missing['OT_needed'][sub] || 0) + 1
it should be
```tsx
(missing['OT_needed']?.[sub] ?? 0)
```

2021-12-01 09:16 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Sorting/index.tsx
> +						...missing['OT_needed'],
It wont since we are already initializing OT_needed and WT_missing with empty objects

2021-12-01 09:17 UTC, hmzahmed commented on web/src/utils/TIP.ts
> +		'Class 5': '3'
Yes

2021-12-01 09:39 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		'Class 5': '3'
Why '3' for class 3-5?

2021-12-03 03:43 UTC, mudssrali approved these changes

2021-12-03 03:44 UTC, merged