Chore: MIS Patch 1
CERP/MIS pull request #486
Opened 2021-12-10 11:57 UTC by hmzahmed

- Add search for fee analytics
- Don't capitalize all letters of school name when printing result cards
- Fix bug where 'leaves' in staff attendance were not calculating correctly

2021-12-12 22:46 UTC, mudssrali requested changes
Thanks @hmzahmed  - Looks good to me - Just a single change need to revert

2021-12-12 22:46 UTC, mudssrali commented on web/src/pages/staff/attendance/single/index.tsx
> +			else {
What if attendance not marked? We don't need to remove explicit checking of attendance status

2021-12-14 09:54 UTC, mudssrali approved these changes
@hmzahmed Thanks - Looks good to me.

2021-12-14 21:57 UTC, merged

2021-12-15 04:06 UTC, ZarishIqbal reviewed
Everything looks good. Just left a few questions.

2021-12-15 04:06 UTC, ZarishIqbal commented on web/src/pages/exams/manage/create.tsx
> +			return Object.keys(classes[classId].sections).includes(studentSectionId)
Should there be null coalescing here?

2021-12-15 04:06 UTC, ZarishIqbal commented on web/src/pages/exams/manage/create.tsx
>  		() => Object.values(getSectionsFromClasses(classes)).sort(classYearSorter),
Null coalescing is mandatory here because `TIP MT Training 1` mein the error i pointed out is because either `getSectionsFromClasses(classes)` returns null or classes are null.