Feature/Peer Groups
CERP/MIS pull request #487
Opened 2021-12-10 12:42 UTC by ZarishIqbal

create peer groups for quizzes

2021-12-12 22:42 UTC, mudssrali requested changes
Thanks @ZarishIqbal - overall good work. I added a few comments where we can improve on.

2021-12-12 22:42 UTC, mudssrali commented on web/src/components/TIP/peer-group-modal.tsx
> +import { defaultPeerGroup } from 'modules/TIP/TIPConstants'
it should be named as `DefaultPeerGroupSize`

2021-12-12 22:42 UTC, mudssrali commented on web/src/components/TIP/peer-group-modal.tsx
> +						{Math.ceil(students.length / state.groupSize)}
It should be `Math.floor`

2021-12-12 22:42 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +	}
we shouldn't do this, instead we can:
```tsx
const selectStudent = (studentId: string) => {
     if(!state.students.includes(studentId)) {
        setState(prevState => ({...prevState, students: [...prevState.students, studentId]}))
     }
}
```

2021-12-12 22:42 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +	}
Instead of complicated logic and anti-pattern, we could simply hold a state for all students like
```tsx
type State = {
  students: { [studentId: string]: boolean }
}

# initialize state with all students of selection false
const [state, setState] = useState<State>({
   students: filtered_students.reduce((agg, std) => return ({...agg, [std.id]: false}), {})
})
```
Now we can write a single state toggle function to select/unselect a student
```tsx
const toggleStudentSelection = (studentId: string) => {
   setState(prevState => ({...prevState, students: { ...prevState.students, [studentId]: !prevState.students[studentId] }}))
}
```
To make Peer Group, we can filter all those students who have selection marked as  `true`

2021-12-12 22:42 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +	const dispatch = useDispatch()
we can move these up after component declaration

2021-12-12 22:42 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +							}}
```tsx
onClick={() => selectAll()}
```

2021-12-12 22:42 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/SingleStdResult.tsx
> +	}, [state.selected])
As we're drilling props to this component, we don't need to update using `useEffect` and keep a state variable

2021-12-12 22:42 UTC, mudssrali commented on web/src/modules/TIP/TIPConstants.ts
> +export const defaultPeerGroup = 4
```ts
export const DefaultPeerGroupSize = 4
```

2021-12-14 05:35 UTC, mudssrali requested changes
A few more changes required, else we're good to merge this into `staging`. Thanks @ZarishIqbal

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/TIPConstants.ts
> +}
Nice ❤️

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +		)
Can we move this dispatch to `action/index.ts` ? I feel grouping action handlers to a separate would make more sense which can help us in different ways.

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +								.map(([id, std]) => id)}
what we're achieving this here? It's better to move this logic down to `PeerGroupModal` if it's necessary. Also instead of doing `filter(...)`, `map(...)`, we can use `reduce(...)` here.

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +				.sort((student, student2) => {
either go with:
```tsx
sort((studentA, studentB))
```
This looks more intuitive
`OR`

```tsx
sort((a, b))
```

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +				.filter(student => state.students[student.id]),
we can do this part inside `reduce(...)` if it is necessary

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +			}
Can you describe this part, what's happening here?

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +					}}
we can move this logic to a separate function

2021-12-14 05:35 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +		dispatch(createPeerGroups(peerGroups, facultyId, quizId))
Nice, you did it here ❤️

2021-12-14 05:45 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +								.map(([id, std]) => id)}
We need an array of student ids. If I filter within map, would that be better?

2021-12-14 05:48 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +			}
We're creating data for merges 
changing `MISStudent[][]` to ->
`{
     pg-1:{
                std1:true,
                std2:true
             }
 }`

2021-12-14 05:48 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +		)
Already done.

2021-12-14 06:03 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +				.filter(student => state.students[student.id]),
We are passing this array to chunkify before reduce so it needs to be filtered before its chunkified.

2021-12-14 09:57 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +								.map(([id, std]) => id)}
`map(...)` expects a return value. In this you're filtering and mapping. `reduce` is the best candidate here which can help us to filter and map students

2021-12-14 09:58 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +			}
Ah meant, describe this logic the code in form of comments

2021-12-14 10:04 UTC, mudssrali approved these changes
Thanks @ZarishIqbal - Looks good to me.
Did you apply check if peer `group size > noOfStudents` somewhere ?

2021-12-14 10:04 UTC, mudssrali commented on web/src/components/TIP/peer-group-modal.tsx
> +	studentsLength: number
Instead of `studentsLength`, we can say e.g. `studentsCount`, `totalStudents`, `noOfStudents`

2021-12-14 10:04 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/SingleStdResult.tsx
> +						onChange={() => selectStudent(student.id)}
I missed that :p however it's nice to see that you refactored it.

2021-12-14 23:55 UTC, merged

2021-12-15 04:30 UTC, ZarishIqbal reviewed
Just left a few questions.

2021-12-15 04:30 UTC, ZarishIqbal commented on web/src/components/TIP/peer-group-modal.tsx
> +							: undefined
Why is this a better approach?

2021-12-15 04:30 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/Result/ResultView.tsx
> +	const noOfStudentsForPeerGrouping = Object.entries(state.students).filter(
We just need the status to filter out students then why are we using `Object.entries` instead of `Object.values`?