Chore: TIP patch 3
CERP/MIS pull request #489
Opened 2021-12-18 04:22 UTC by ZarishIqbal

- update search algorithm for class and group view
- fix error in sorting: all students being sorted into remediation not needed
- add checks for reassignment 
- fix and update sorting history 
- fix tags for class and group view 
- fix results by getting all test ids instead of 1

2021-12-18 05:45 UTC, mudssrali requested changes
Thanks @ZarishIqbal  - There is a lot of improvements for naming variable, logical constructs and so on 👍🏻  👍🏻 Keep up. I suggested a few changes and questions in comments

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
> +		const is_oral = selectedGrade === 'Oral Test' ? true : current_oral_value
Here we can improve:
```tsx
const isOral = selectedGrade === 'Oral Test' || currentOralValue
```

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
> +		} = std.targeted_instruction?.learning_level?.[selectedSubject] || {
instead of `||` we can use `??`

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
> +		const timestamp = moment().valueOf()
Why we're using this `moment().valueOf()` ? Instead we can get the current timestamp in unix format as
```tsx
const timtestamp = Date.now()
```
Or if with moment
```tsx
const timestamp = moment().now()
```

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
> +					{modalType === ModalType.ASSIGNED_GROUPS_INFO && (
thanks

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/ClassViewCard.tsx
> -)(ClassViewCard)
👍🏻 💯

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/index.tsx
> +					{sortedSections.map((classObj, index) => {
```tsx
{ sortedSections.map(section, index)}
```

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/ClassView/index.tsx
> +							<option key={index} value={classObj.id}>
Instead of `index` which has value between `(1...n)`, we should always go for more suitable `unique` key. Here in case section.id or section.class_id best fit

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileGroupView.tsx
> +			!learning_level?.history?.[sortedHistory[sortedHistory.length - 1][0]]?.grade
We could turn this into a simple function call to return us grade

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/DiagnosticTest/Result/Result.tsx
> +		.map(([id, test]) => id)
As we changed the logic here, we should update the comment and write additional information why we did this and what we're achieving here.

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/FormativeTest/Grading.tsx
> +					const timestamp = new Date().valueOf()
here again we can use
```tsx
Date.now()
```
Here you can read more about it: https://stackoverflow.com/a/33184154/8108770

2021-12-18 05:45 UTC, mudssrali commented on web/src/modules/TIP/FormativeTest/Result/ResultCards/Result.tsx
> +	const testIds = Object.entries(props.targeted_instruction.tests)
```tsx
Object.entries(props.targeted_instruction.tests ?? {})
```

2021-12-18 05:45 UTC, mudssrali commented on web/src/utils/TIP.ts
> +				return q?.grade === '1'
we don't need to do `q?.grade`, simply `q.grade` because we've early return guard if question is undefined

2021-12-18 05:45 UTC, mudssrali commented on web/src/utils/TIP.ts
> +						if (agg2 && agg2.slo_obj && agg2.slo_obj[sloCategory]) {
Good place to use `optional-chaining`
```tsx
if (agg2?.slo_obj?.[sloCategory])
```

2021-12-18 05:45 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		{
It should be a `number` type, no? we're storing timestamp in form of integer.

2021-12-18 05:45 UTC, mudssrali commented on web/src/utils/TIP.ts
> +	return moment(b[0], 'x').diff(moment(a[0], 'x'))
we know that it's `unix-timestamp` which is stored in form of number, we can do simple math
```tsx
return b[0] - a[0]
```

2021-12-18 05:45 UTC, mudssrali commented on web/src/utils/TIP.ts
> +			)
First, Instead of `gradeObj`, we can simply use `grade` or `gradingDetails`

2021-12-18 07:20 UTC, ZarishIqbal commented on web/src/utils/TIP.ts
> +		{
The previous dates were store in `YYYY-MM-DD` format. So I didn't do it.

2021-12-18 07:51 UTC, ZarishIqbal commented on web/src/utils/TIP.ts
> +	return moment(b[0], 'x').diff(moment(a[0], 'x'))
This sorter is getting date from `Object.entries()` which returns `[string,value]`. Am I right? I have done `parseInt`

2021-12-19 05:45 UTC, mudssrali commented on web/src/utils/TIP.ts
> +	return moment(b[0], 'x').diff(moment(a[0], 'x'))
ah got it.

2021-12-19 05:50 UTC, mudssrali approved these changes
Thank @ZarishIqbal  Looks good to me 👍🏻  - We're good to merge this into staging now.

2021-12-19 05:50 UTC, merged