Chore: TIP - Quiz module changes
CERP/MIS pull request #500
Opened 2021-12-28 09:28 UTC by ZarishIqbal

- design tweaks 
- add reset quiz option for each student
- add one source of truth for quizzes taken
- remove `no change to save` pop up on quiz grading
- update quiz threshold

2021-12-29 20:10 UTC, mudssrali requested changes
Thanks @ZarishIqbal  - Good efforts. I commented a few things, two of them needs to be point to ponder.
- Optional Chaining for `targeted_instruction`
- Obtained_marks possible value

We can talk about this in-person tomorrow.

2021-12-29 20:10 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +				obtainedMarks === undefined || obtainedMarks < 0
```
!obtainedMarks || obtainedMarks < 0
```
Should we do  `!obtainedMarks`  here ? What we would do if obtainedMarks: `'' | 0 |  'undefined'`

2021-12-29 20:10 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +						obtainedMarks === undefined || obtainedMarks < 0
again here

2021-12-29 20:10 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +					{obtainedMarks !== undefined && obtainedMarks > -1 && (
are we dealing `obtainedMarks: 0` differently? bc we could simply obtainedMarks && ( ). I feel obtainedMarks can only be `empty-string | undefined | 0 | -1 | >0`

2021-12-29 20:10 UTC, mudssrali commented on web/src/utils/TIP.ts
> +		return `${obtainedMarks}` !== ''
Can we improve this logic?

2021-12-29 20:54 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/Grading.tsx
> +				[student.id]: obtained_marks !== '' ? obtained_marks : undefined
Obtainedmarks type is `number`. However in db, obtainedmarks type is `string`. And for some students it is  '' instead of undefined.

2021-12-30 04:52 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +				obtainedMarks === undefined || obtainedMarks < 0
`obtainedMarks` is passed as a param here. I have made sure in the parent component the it would either be a `number` or `undefined`

2021-12-30 04:54 UTC, ZarishIqbal commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +					{obtainedMarks !== undefined && obtainedMarks > -1 && (
obtainedMarks can be from `0 - 10` 
`10` being the total marks
`-1` is for absents
`undefined | ''` is for not graded

2021-12-30 04:55 UTC, ZarishIqbal commented on web/src/utils/TIP.ts
> +		return `${obtainedMarks}` !== ''
How so?

2021-12-31 07:53 UTC, mudssrali requested changes
Thanks @ZarishIqbal  - Looks good to me however I left a few comments

2021-12-31 07:53 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Grading.tsx
> +	const quizTitle = targetedInstruction?.quizzes?.[class_name]?.[subject]?.[quiz_id]?.quiz_title
instead of doing this we can get quiz and from quiz we can get total marks and title

2021-12-31 07:53 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +								'opacity-30 dark': !obtainedMarks || obtainedMarks < 0
As you mentioned above obtainedMarks can be `undefined` and `0` and we have different logic around 0 or undefined, we should stick to `obtainedMarks === undefined` because if obtained marks 0, `!obtainedMarks` would result in true

2021-12-31 07:53 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +						!obtainedMarks || obtainedMarks < 0
here also - revert to previous checks

2022-01-02 02:31 UTC, mudssrali approved these changes
Now it looks good - Thanks @ZarishIqbal

2022-01-02 02:31 UTC, merged