Chore: Tip - Show unsynced changes
CERP/MIS pull request #513
Opened 2022-01-17 14:52 UTC by ZarishIqbal

- Add catch to fetchTargetedInstruction
- Add unsynced icon and count to TIP Header

2022-01-21 12:21 UTC, mudssrali requested changes
Thanks @ZarishIqbal  - Nice work. Just a few suggestion and a single change.

2022-01-21 12:21 UTC, mudssrali commented on web/src/modules/TIP/Header.tsx
> +	)
we can do this as well, which is more intuitive
```tsx
const queuedChanges = useSelector((state) => Object.key(state.queued.mutations).length)
```

2022-01-21 12:21 UTC, mudssrali commented on web/src/modules/TIP/Header.tsx
> +										<img className="h-8" src={TIP} />
missing `alt` attribute

2022-01-21 12:21 UTC, mudssrali commented on web/src/modules/TIP/Header.tsx
> +																	You are not online
```txt
You are offline
```
OR
```txt
You are not online
```

2022-01-21 12:21 UTC, mudssrali commented on web/src/modules/TIP/Header.tsx
> +																	}}>
are we sure about `timeout: 1000` ? If yes, We don't need to have `setReconnecting(true)` bc it would create bad UX.

2022-01-24 13:45 UTC, ZarishIqbal commented on web/src/modules/TIP/Header.tsx
> +																	}}>
The design has a reconnecting spinner. Timeout is to show that spinner and then reload the page.

2022-01-25 11:37 UTC, mudssrali approved these changes
Thanks @ZarishIqbal

2022-02-04 12:57 UTC, hmzahmed approved these changes

2022-02-04 15:03 UTC, merged