Chore: TIP-HT Dashboard Changes
CERP/MIS pull request #518
Opened 2022-01-27 10:40 UTC by salehcerp

### Fixed 

- changed levels to progress
- show null instead of NaN in HT Dashboard

2022-01-27 15:28 UTC, hmzahmed requested changes
Congrats on your first PR, Nice work!! everything looks good. Just a few suggestions

2022-01-27 15:28 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Tests/SummativeTest/index.tsx
> +											<div className="">
What purpose is this div serving?

2022-01-27 15:28 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Tests/SummativeTest/index.tsx
> +												</button>
This UI element is not doing any action nor does it need any click functionality, we can change this from button to div

2022-01-27 15:28 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Tests/SummativeTest/index.tsx
> +						{Object.entries(items).map(([k, item], index) => {
you can rename the variable 'k' to 'grade', we should always name variables something descriptive, 'item' can also be renamed to 'result'

2022-01-27 15:28 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Tests/SummativeTest/index.tsx
> +									className="grid grid-cols-4 my-2 justify-items-center">
We should avoid using index as key if we can, here we can use grade as index

2022-01-27 15:28 UTC, hmzahmed commented on web/src/modules/TIP/HTDashboard/Tests/SummativeTest/index.tsx
> +												</button>
We should also provide a key whenever we render a list of elements, here we can provide a key by concatenating grade and subject

2022-02-07 13:22 UTC, mudssrali approved these changes
Looks good to me. Thanks @salehcerp

2022-02-07 13:45 UTC, closed without merging