grade slidebar refactor
CERP/MIS pull request #519
Opened 2022-02-03 14:09 UTC by salehcerp

- improvement in UI appearance of slide-bar

2022-02-04 12:55 UTC, hmzahmed requested changes
Just 1 comment, let Zarish know about this comment and confirm with her before making any change

2022-02-04 12:55 UTC, hmzahmed commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +								` flex justify-center items-center text-white rounded-md w-max px-4 h-8 shadow-lg absolute transform -translate-y-7 translate-x-${getTranslateValue(
I think we should leave the padding for x-axis at 2 since we need the slider to take as much space as possible

2022-02-04 13:16 UTC, salehcerp commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +								` flex justify-center items-center text-white rounded-md w-max px-4 h-8 shadow-lg absolute transform -translate-y-7 translate-x-${getTranslateValue(
with padding 2 the marks were getting a bit weird in display so changed this to 4 and shown the changes and resulted UI to @ZarishIqbal

2022-02-07 13:24 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/SingleStdGrading.tsx
> +								` flex justify-center items-center text-white rounded-md w-max px-4 h-8 shadow-lg absolute transform -translate-y-7 translate-x-${getTranslateValue(
@ZarishIqbal  can you leave your thoughts here?

2022-02-07 13:45 UTC, ZarishIqbal approved these changes
Looks good to me. LGTM!

2022-02-07 13:57 UTC, mudssrali approved these changes
Thanks @salehcerp

2022-02-07 13:58 UTC, merged