Chore: TIP patch 4
CERP/MIS pull request #520
Opened 2022-02-04 15:18 UTC by ZarishIqbal

### Added
- add oral test finish model
- add answer key for quizzes

### Fixed
- update tip helpline number
- fix reset grade in starting, summative & oral test
- fix comparison matrix 
- sort quiz results to `Ungraded, Struggling, Working, Mastered, Absent`
- add icons for ungraded and absent to quiz results 
- add icons for ungraded and absent to peer group
- design changes

2022-02-08 13:24 UTC, mudssrali requested changes
Thanks @ZarishIqbal  -  Overall good work -  A few suggestions and changes request.

`Note`: I would suggest everyone at team don't create PR with these many file changes. It's very hard and lengthy process to review PR and keep a focus on what's going on in this PR. Breakdown into multiple PRs and work.

2022-02-08 13:24 UTC, mudssrali commented on web/src/components/TIP/oral-test-finish-modal.tsx
> +}
setIsComponentVisible is just a simple function so we can do
```tsx
setIsComponentVisible: () => void
```
and from where we passing down to this component we can do:

```
setIsComponentVisible = { () => setIsComponentVisible(toggle) }
```

2022-02-08 13:24 UTC, mudssrali commented on web/src/components/TIP/oral-test-finish-modal.tsx
> +					onClick={() => setIsComponentVisible(false)}>
here we can simply do:
```tsx
onClick={ setIsComponentVisble }
```

2022-02-08 13:24 UTC, mudssrali commented on web/src/components/TIP/percentage-box.tsx
> +			{validatePercentage(percentage) && `${percentage} %`}
We can improve this.

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/DiagnosticTest/Result/Result.tsx
>  	const { section_id, subject, class_name } = match.params as Params
there's a hook that we can use e.g. useParams from `react-router-dom`

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/DiagnosticTest/Result/index.tsx
>  		.reduce<Record<string, boolean>>(
all .filter().map.reduce() can be done in reduce()

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/FormativeTest/InsertGrades.tsx
> +	const { class_name, subject, section_id, test_id } = match.params as Params
we can use useParams hook here as well

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/FormativeTest/InsertGrades.tsx
> +							std.targeted_instruction.results[test_id]
this can be done like
```tsx
const chekced = std.targeted_instruction?.results?.[testId]
```

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/group-view.tsx
> +		[test_type: string]: {
[testType: string]

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/group-view.tsx
> +				items.map(item => (
we don't need to add a check here

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/group-view.tsx
> +							/>
we would definitely build a reusable image component

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/skill-view.tsx
> +		[test_type: string]: {
`[testType]`

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/skill-view.tsx
> +					student.targeted_instruction.learning_level[subject]?.grade ?? 'Not Graded'
```tsx
const studentGrade = student?.targeted_instruction?.learning_level?.[subject]?.grade ?? 'Not Graded'

```

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/skill-view.tsx
> +						}
can we simplify this?

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/HTDashboard/Tests/SummativeTest/index.tsx
> +				([, result]) => result.type === 'Summative'
nice, thanks

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/Quizzes/Result/PeerGroupView.tsx
> +			return ''
when we're returning, no need to have if else

2022-02-08 13:24 UTC, mudssrali commented on web/src/modules/TIP/TIPSupport.tsx
> +		answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempor sit amet urna vel porta. Morbi euismod consequat enim, nec suscipit sapien porta non. Integer magna sem, lacinia ut ulla
we need to tell the source of these questions to put them here and finally deployed. @ZarishIqbal  - this important

2022-02-09 17:32 UTC, ZarishIqbal commented on web/src/components/TIP/percentage-box.tsx
> +	}
@mudssrali 
We cannot use that 
```js 
export const parseNumber = (number: string) => {
	const parsedNumber = parseFloat(number)
	if (isNaN(parsedNumber)) {
		return 0
	}
	return parsedNumber
}
```
In this case, 0 means that the student's percentage is 0. Undefined means that the student is ungraded. If we user `parseNumber`, we cannot differentiate.

2022-02-09 17:33 UTC, ZarishIqbal commented on web/src/components/TIP/percentage-box.tsx
> +			{validatePercentage(percentage) && `${percentage} %`}
How so?

2022-02-10 08:52 UTC, ZarishIqbal commented on web/src/modules/TIP/HTDashboard/Tests/ComparisonMatrix/group-view.tsx
> +				items.map(item => (
I agree. I didn't refactor the logic in the files actually just divided the huge file into 3 files to simplify.

2022-02-10 09:06 UTC, mudssrali commented on web/src/components/TIP/percentage-box.tsx
> +	}
make sense @ZarishIqbal

2022-02-10 09:39 UTC, ZarishIqbal commented on web/src/modules/TIP/TIPSupport.tsx
> +		answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempor sit amet urna vel porta. Morbi euismod consequat enim, nec suscipit sapien porta non. Integer magna sem, lacinia ut ulla
What we discussed was that we'll add  faqs in tip.json and fetch the questions from there. They need to provide us a csv with `question` `answer` `link -> for videos`

2022-02-11 11:07 UTC, mudssrali approved these changes

2022-02-11 11:08 UTC, merged