Chore: TIP - Oral Test Fixes
CERP/MIS pull request #528
Opened 2022-02-23 13:32 UTC by ZarishIqbal

### This PR contains:

- [x] restrict manual assignment in `class view` for `oral test`
- [x] show the students' sorting result as `Not Graded` instead of `Oral Test` in class view
- [x] show marked and unmarked students in oral tests finish grading page

2022-02-23 15:14 UTC, mudssrali requested changes
Thanks @ZarishIqbal  for the changes - most of stuff looks fine to me however a few change requested in form of comments.

2022-02-23 15:14 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentInfoModal.tsx
> +				)
thumb rule: always filter first then sort later
+ naming convention instead of `grade_obj`, change to `grade`. we've ts working space.

2022-02-23 15:14 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentInfoModal.tsx
> +					const grade = convertLearningGradeToGroupName(grade_obj.grade)
same goes here.

2022-02-23 15:14 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileClassView.tsx
> +					{Object.entries(learning_levels || {})
instead of ||, use ??

2022-02-23 15:14 UTC, mudssrali commented on web/src/modules/TIP/DetailedAnalysis/Modals/StudentProfileClassView.tsx
> +							const is_oral = grade_obj.is_oral ? true : false
isOral

2022-02-23 15:44 UTC, ZarishIqbal commented on web/src/utils/TIP.ts
> +	students: RootDBState['students']
Its getting the students through section id (not marked one) .. using `testId` we're getting the marked students.

2022-02-25 13:47 UTC, ZarishIqbal commented on web/src/utils/TIP.ts
> +	students: RootDBState['students']
@mudssrali can we merge it? I made the requested changes

2022-02-25 18:00 UTC, mudssrali commented on web/src/utils/TIP.ts
> +	students: RootDBState['students']
yes

2022-02-25 18:01 UTC, mudssrali approved these changes

2022-02-25 18:01 UTC, merged